export default function LogisticaPage(){
    return(
        <div>
            logistica
            <br></br>
            logistica
            <br></br>
            logistica
            <br></br>
            logistica
            <br></br>
            logistica
            <br></br>
            logistica
            <br></br>
            logistica
            <br></br>
            logistica
            <br></br>
            logistica
            <br></br>
        </div>
    )
}